add API
KsUsha737/Graduation_project pull request #3
Opened 2022-08-20 13:04 UTC by KsUsha737

2022-08-22 17:29 UTC, VladimirVolkovD commented on src/test/java/API/apiClient/LeadClientApi.java
> +    }
отредактируй пустые строки отдели методы от методов пустой строкой

2022-08-22 17:30 UTC, VladimirVolkovD commented on src/test/java/API/base/BaseApi.java
> +                        .concat(url))
tokenInfo.getInstanceUrl()
                        .concat("/services/data/v55.0/sobjects/")
                        .concat(url)
                        
                         эта часть повторяется в каждом методе добавь получение токена в конструктор класса в таком случае чтобы не дублировать код

2022-08-22 17:31 UTC, VladimirVolkovD commented on src/test/java/API/dto/CreatedLeadResponse.java
> +    @SerializedName("id")
то что аннотация  Expose  нужна я согласен а на счет сериалайз нейм в случае если ия совпадает с полем не уверен, чаще он используется если нейминги не совпдаюат мне кажется будет и без него работать

2022-08-22 17:33 UTC, VladimirVolkovD commented on src/test/java/tests/API/TestLead.java
> +        LeadClientApi leadClientApi = new LeadClientApi();
lead client api  в каждом тесте сделай сетап метод для класса или создай бейс апи и туда запихнуть создание всех апи нужных и от него отнаследоваться

2022-08-22 17:34 UTC, VladimirVolkovD commented on src/test/java/tests/API/TestLead.java
> +                .company("Home")
один и тот же пользователь создается в каждом тесте давай избавимся от дублирования создай его перед всеми тестами в бефор методе

2022-08-22 17:35 UTC, VladimirVolkovD requested changes
оставил пару коментов

2022-08-23 18:24 UTC, KsUsha737 commented on src/test/java/API/dto/CreatedLeadResponse.java
> +    @SerializedName("id")
поправила

2022-08-24 07:00 UTC, VladimirVolkovD approved these changes

2022-08-25 18:07 UTC, merged